service: firehose-transformations
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, 'eu-central-1'}
  stage: ${opt:stage, 'dev'}
  timeout: 60
  memorySize: 128

functions:
  fix-newline:
    handler: index.fixNewline
