service: tracker-app

useDotenv: true

frameworkVersion: '3'

custom:
  ROLE_ARN: ${env:FIREHOSE_TRACKER_ROLE_ARN}
provider:
  name: aws
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  memorySize: 160
  timeout: 29
  environment:
    FIREHOSE_TRACKER_ROLE_ARN: ${self:custom.ROLE_ARN}
    FIREHOSE_TRACKER_FIX_NEWLINE_LAMBDA_ARN: ${env:FIREHOSE_TRACKER_FIX_NEWLINE_LAMBDA_ARN}
    FIREHOSE_TRACKER_LOG_GROUP_NAME: ${env:FIREHOSE_TRACKER_LOG_GROUP_NAME}
    FIREHOSE_TRACKER_BUCKET_ARN: ${env:FIREHOSE_TRACKER_BUCKET_ARN}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "iam:PassRole"
          Resource:
            - ${self:custom.ROLE_ARN}
      managedPolicies:
        - "arn:aws:iam::aws:policy/AmazonKinesisFirehoseFullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"


functions:
  tracker:
    handler: main.handler
    events:
      - httpApi:
          path: /track
          method: post
      - httpApi:
          path: /health
          method: get

plugins:
  - serverless-python-requirements
  - serverless-offline