service: tracker-app

useDotenv: true

frameworkVersion: '3'

custom:
  ROLE_ARN: { 'Fn::Join': [ ':', [ 'arn:aws:iam:', { 'Ref': 'AWS::AccountId' }, 'role/FirehoseAssumeRole' ] ] }
  FIX_NEWLINE_LAMBDA_NAME: firehose-transformations-${self:provider.stage}-fix-newline:3
  FIX_NEWLINE_LAMBDA_ARN: { 'Fn::Join': [ ':', [ 'arn:aws:lambda', { 'Ref': 'AWS::Region' }, { 'Ref': 'AWS::AccountId' }, 'function', '${self:custom.FIX_NEWLINE_LAMBDA_NAME}' ]] }

provider:
  name: aws
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  memorySize: 160
  timeout: 29
  environment:
    FIREHOSE_TRACKER_ROLE_ARN: ${self:custom.ROLE_ARN}
    FIREHOSE_TRACKER_FIX_NEWLINE_LAMBDA_ARN: ${self:custom.FIX_NEWLINE_LAMBDA_ARN}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "iam:PassRole"
          Resource:
            - ${self:custom.ROLE_ARN}
      managedPolicies:
        - "arn:aws:iam::aws:policy/AmazonKinesisFirehoseFullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"


functions:
  tracker:
    handler: main.handler
    events:
      - httpApi:
          path: /track
          method: post
      - httpApi:
          path: /health
          method: get

plugins:
  - serverless-python-requirements
  - serverless-offline